package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Food;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    Food selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    List<Food> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    int updateByPrimaryKey(Food record);
}