package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Animal;
import lt.vu.mybatis.model.Shelter;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface ShelterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHELTER
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHELTER
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    int insert(Shelter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHELTER
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    Shelter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHELTER
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    List<Shelter> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHELTER
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    int updateByPrimaryKey(Shelter record);

    List<Animal> selectOtherAnimals(Long id);
}