package lt.vu.mybatis.model;

public class Animal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.TYPE
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.SHELTER_ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    private Long shelterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.ID
     *
     * @return the value of PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.ID
     *
     * @param id the value for PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @return the value of PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.NAME
     *
     * @param name the value for PUBLIC.ANIMAL.NAME
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.TYPE
     *
     * @return the value of PUBLIC.ANIMAL.TYPE
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.TYPE
     *
     * @param type the value for PUBLIC.ANIMAL.TYPE
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.SHELTER_ID
     *
     * @return the value of PUBLIC.ANIMAL.SHELTER_ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public Long getShelterId() {
        return shelterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.SHELTER_ID
     *
     * @param shelterId the value for PUBLIC.ANIMAL.SHELTER_ID
     *
     * @mbg.generated Mon May 02 21:17:02 EEST 2022
     */
    public void setShelterId(Long shelterId) {
        this.shelterId = shelterId;
    }
}