package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Shelter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHELTER.ID
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHELTER.ADDRESS
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHELTER.NAME
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    private String name;

    @Getter
    @Setter
    private List<Animal> animals;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHELTER.ID
     *
     * @return the value of PUBLIC.SHELTER.ID
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHELTER.ID
     *
     * @param id the value for PUBLIC.SHELTER.ID
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHELTER.ADDRESS
     *
     * @return the value of PUBLIC.SHELTER.ADDRESS
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHELTER.ADDRESS
     *
     * @param address the value for PUBLIC.SHELTER.ADDRESS
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHELTER.NAME
     *
     * @return the value of PUBLIC.SHELTER.NAME
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHELTER.NAME
     *
     * @param name the value for PUBLIC.SHELTER.NAME
     *
     * @mbg.generated Mon May 02 21:17:03 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}